/**
 * ============================================================
 * PROJECT DATA LAYER — Phase 2 Merged Source
 * ============================================================
 *
 * This file is the SINGLE source consumed by all portfolio pages.
 *
 * Data sources (in merge order):
 *   1. src/data/generated-projects.json
 *      ↳ Auto-generated by `npm run sync:github`
 *      ↳ Populated from GitHub repositories tagged: "portfolio"
 *      ↳ DO NOT edit generated-projects.json manually.
 *
 *   2. src/data/manual-projects.ts  (optional overrides / additions)
 *      ↳ For projects that live outside GitHub or need extra
 *        metadata not available from the GitHub API.
 *      ↳ Manual projects take precedence over generated ones
 *        if they share the same slug.
 *
 * Merge rules:
 *   - Manual project with same slug → replaces generated entry
 *   - Manual project with unique slug → appended to list
 *   - Generated entries without a matching manual entry → kept as-is
 *
 * ============================================================
 */

import generatedData from './generated-projects.json';
import { manualProjects } from './manual-projects';
import { baselineProjects } from './baselineProjects';

// ─── Shared Type Definitions ──────────────────────────────────

export interface ProjectDocumentation {
  architecture?: string;
  api?: string;
  deployment?: string;
  general?: string;
}

export interface ProjectBlog {
  title?: string;
  url?: string;
}

export interface DesignDecision {
  title: string;
  description: string;
}

export interface GitHubMetadata {
  stars: number;
  forks: number;
  language?: string;
  updatedAt: string;
}

export interface Project {
  slug: string;
  title: string;
  category: 'Distributed Systems' | 'Backend' | 'Cloud' | 'DevOps' | 'AI Systems';
  featured: boolean;
  description: string;
  longDescription?: string;
  technologies: string[];
  github?: string;
  demo?: string;
  documentation?: ProjectDocumentation;
  blog?: ProjectBlog;
  architectureImage?: string;
  problem?: string;
  solution?: string;
  challenges?: string[];
  decisions?: DesignDecision[];
  status?: 'Completed' | 'Active' | 'In Progress';
  date?: string;
  order?: number;
  githubMetadata?: GitHubMetadata;
  _source?: 'github' | 'manual';
}

// ─── Merge Logic ──────────────────────────────────────────────

const generatedProjects: Project[] = (generatedData.projects || []) as Project[];

// Build a lookup of manual projects by slug for O(1) override checks
const manualBySlug = new Map(manualProjects.map(p => [p.slug, p]));

// Start with generated projects, replacing any that have a manual override
const mergedFromGenerated = generatedProjects.map(gp =>
  manualBySlug.has(gp.slug) ? { ...gp, ...manualBySlug.get(gp.slug), _source: 'manual' as const } : gp
);

// Add manual projects that have slugs NOT present in generated list
const generatedSlugs = new Set(generatedProjects.map(p => p.slug));
const additionalManual = manualProjects.filter(mp => !generatedSlugs.has(mp.slug));

// Final merged list (falls back to baseline showcase projects if no projects exist yet)
let allProjects: Project[] = [...mergedFromGenerated, ...additionalManual];
if (allProjects.length === 0) {
  allProjects = [...baselineProjects];
}

// Sort: by order (ascending), then featured (featured first), then date (newest first)
allProjects.sort((a, b) => {
  const orderA = typeof a.order === 'number' ? a.order : 999;
  const orderB = typeof b.order === 'number' ? b.order : 999;
  if (orderA !== orderB) return orderA - orderB;
  if (a.featured !== b.featured) return b.featured ? 1 : -1;
  return (b.date || '').localeCompare(a.date || '');
});

export const projects: Project[] = allProjects;

export const projectCategories = [
  'All',
  'Distributed Systems',
  'Backend',
  'Cloud',
  'DevOps',
  'AI Systems',
] as const;
